export enum LobbySend {
    // -----事件-----
    // 連線
    LOBBY_CONNECTION = 'lobby_connection',
    LOBBY_QUICK_LOGIN = 'lobby_protocol_quickLogin',
    // 錯誤
    LOBBY_ERROR = 'lobby_error',
    PROTOCOL_ERROR = 'lobby_protocol_error',
    // 帳號
    LOBBY_ACCOUNT = 'lobby_account',
    PROTOCOL_ACCOUNT_GET_USER_INFO = 'lobby_protocol_account_getUserInfo',
    PROTOCOL_ACCOUNT_CHANGE_USER_NAME = 'lobby_protocol_account_changeUserName',
    PROTOCOL_ACCOUNT_CHECK_PASSWORD = 'lobby_protocol_account_checkPassword',
    PROTOCOL_ACCOUNT_CHANGE_PASSWORD = 'lobby_protocol_account_changePassword',
    PROTOCOL_ACCOUNT_BIND_EMAIL = 'lobby_protocol_account_bindEmail',
    PROTOCOL_ACCOUNT_CANCEL_BIND_EMAIL = 'lobby_protocol_account_cancelBindEmail',
    PROTOCOL_ACCOUNT_CHANGE_EMAIL = 'lobby_protocol_account_changeEmail',
    PROTOCOL_ACCOUNT_CHANGE_AVATAR = 'lobby_protocol_account_changeAvatar',
    PROTOCOL_ACCOUNT_BUYVIP = 'lobby_protocol_account_buyVIP',
    // 公告
    LOBBY_ACCOUNCEMENT = 'lobby_announcement',
    PROTOCOL_ANNOUNCEMENT_GET_LIST = 'lobby_protocol_announment_getList',
    // 生涯
    LOBBY_CAREER = 'lobby_career',
    PROTOCOL_CAREER_GET_NLH_NORMAL = 'lobby_protocol_career_getNLHNormal',
    PROTOCOL_CAREER_GET_NLH_SNG = 'lobby_protocol_career_getNLHSNG',
    PROTOCOL_CAREER_GET_NLH_MTT = 'lobby_protocol_career_getNLHMTT',
    // 一般
    LOBBY_GENERAL = 'lobby_general',
    PROTOCOL_GENERAL_GET_RULE_LIST = 'lobby_protocol_general_getRuleList',
    PROTOCOL_GENERAL_GET_TABLE_TYPE = 'lobby_protocol_general_getTableType',
    PROTOCOL_GENERAL_GET_ITEM_LIST = 'lobby_protocol_general_getItemList',
    PROTOCOL_GENERAL_USE_ITEM = 'lobby_protocol_general_useItem',
    PROTOCOL_GENERAL_GET_TABLE_LIST = 'lobby_protocol_general_getTableList',
    PROTOCOL_GENERAL_GET_EMAIL_LIST = 'lobby_protocol_general_getEmailList',
    PROTOCOL_GENERAL_READ_EMAIL = 'lobby_protocol_general_readEmail',
    PROTOCOL_GENERAL_DELETE_EMAIL = 'lobby_protocol_general_deleteEmail',
    PROTOCOL_GENERAL_GETVIP = 'lobby_protocol_general_getVIP',
    PROTOCOL_GENERAL_FEEBACK = 'lobby_protocol_general_feeback',
    PROTOCOL_GENERAL_FEEBACK_RECORD = 'lobby_protocol_general_feeback_record',
    PROTOCOL_GENERAL_GETMSG = 'lobby_protocol_getMsg',
    // 商城
    LOBBY_SHOP = 'lobby_shop',
    PROTOCOL_SHOP_GET_ITEM_LIST = 'lobby_protocol_shop_getItemList',
    // 俱樂部管理
    CLUB_ADMIN = 'club_admin',
    PROTOCOL_CLUB_CREATE = 'lobby_protocol_club_create',
    PROTOCOL_CLUB_EDIT = 'lobby_protocol_club_edit',
    PROTOCOL_CLUB_RESET_IMG = 'lobby_protocol_club_reset_img',
    PROTOCOL_CLUB_SEARCH = 'lobby_protocol_club_search',
    PROTOCOL_CLUB_JOIN = 'lobby_protocol_club_join',
    PROTOCOL_CLUB_QUIT = 'lobby_protocol_club_quit',
    PROTOCOL_CLUB_DISBAND = 'lobby_protocol_club_disband',
    PROTOCOL_CLUB_GET_TABLE_LIST = 'lobby_protocol_club_getTableList',
    PROTOCOL_CLUB_GET_MEMBER_LIST = 'lobby_protocol_club_getMemberList',
    PROTOCOL_CLUB_AGREE_JOIN = 'lobby_protocol_club_agreeJoin',
    PROTOCOL_CLUB_REFUSE_JOIN = 'lobby_protocol_club_refuseJoin',
    PROTOCOL_CLUB_GET_MEMBER = 'lobby_protocol_club_getMember',
    PROTOCOL_CLUB_CHANGE_MEMBER_TYPE = 'lobby_protocol_club_changeMemberType',
    PROTOCOL_CLUB_DELETE_MEMBER = 'lobby_protocol_club_deleteMember',
    PROTOCOL_CLUB_MEMBER_REMARKS = 'lobby_protocol_club_memberRemarks',
    PROTOCOL_CLUB_GET_JOIN_CLUB = 'lobby_protocol_club_getJoinClub',
    PROTOCOL_CLUB_GET_CLUB_DETAIL = 'lobby_protocol_club_getClubDetail',
    PROTOCOL_CLUB_GET_ADMIN_DATA = 'lobby_protocol_club_getAdminData',
    PROTOCOL_CLUB_MESSAGE_PUSH = 'lobby_protocol_club_messagePush',
    PROTOCOL_CLUB_MESSAGE_RECEIVE = 'lobby_protocol_club_messageReceive',
    PROTOCOL_CLUB_GET_MEMBER_CREDIT_LOG = 'lobby_protocol_club_getMemberCreditLog',
    PROTOCOL_CLUB_GET_JACKPOT = 'lobby_protocol_club_getJackpot',
    PROTOCOL_CLUB_DEPOSIT_JACKPOT = 'lobby_protocol_club_depositJackpot',
    PROTOCOL_CLUB_JACKPOT_RECORD = 'lobby_protocol_club_JackpotRecord',
    PROTOCOL_CLUB_GET_LEVEL_UP_CLUB_DETAIL = 'lobby_protocol_club_getLevelUpClubDetail',
    PROTOCOL_CLUB_LEVEL_UP_CLUB = 'lobby_protocol_club_levelUpClub',
    // 俱樂部櫃台
    CLUB_COUNTER = 'club_counter',
    PROTOCOL_CLUB_SEARCH_POINT = 'lobby_protocol_club_searchPoint',
    PROTOCOL_CLUB_SEND_OUT = 'lobby_protocol_club_sendOut',
    PROTOCOL_CLUB_CLAIM_BACK = 'lobby_protocol_club_claimBack',
    PROTOCOL_CLUB_TRADE_RECORD = 'lobby_protocol_club_tradeRecord',
    PROTOCOL_CLUB_SEND_GIFT = 'lobby_protocol_club_sendGift',
    PROTOCOL_CLUB_SEND_OUT_PROXY_POINT = 'lobby_protocol_club_sendOutProxyPoint',
    PROTOCOL_CLUB_CLAIM_BACK_PROXY_POINT = 'lobby_protocol_club_claimBackProxyPoint',
    PROTOCOL_CLUB_POINT = 'lobby_protocol_club_point',
    PROTOCOL_CLUB_BUY_POINT = 'lobby_protocol_club_buyPoint',
    // 俱樂部數據
    CLUB_DATA = 'club_data',
    PROTOCOL_CLUB_GET_DIGITAL_DATA = 'lobby_protocol_club_getDigitalData',
    PROTOCOL_CLUB_EXPORT_DATA = 'lobby_protocol_club_exportData',
    // 俱樂部郵箱
    CLUB_EMAIL = 'club_email',
    PROTOCOL_CLUB_GET_EMAIL_LIST = 'lobby_protocol_club_getEmailList',
    PROTOCOL_CLUB_READ_EMAIL = 'lobby_protocol_club_readEmail',
    PROTOCOL_CLUB_DELETE_EMAIL = 'lobby_protocol_club_deleteEmail',
    // 俱樂部會員
    CLUB_MEMBER = 'club_member',
    PROTOCOL_CLUB_GET_PROXY_MESSAGE = 'lobby_protocol_club_getProxyMessage',
    PROTOCOL_CLUB_GET_PROXY_DOWNSTREAM = 'lobby_protocol_club_getProxyDownstream',
    PROTOCOL_CLUB_GET_PROXY_CREDIT = 'lobby_protocol_club_getProxyCredit',
    PROTOCOL_CLUB_SET_PROXY_DOWNSTREAM = 'lobby_protocol_club_setProxyDownstream',
    // NLH遊戲
    GAME_NLH = 'game_nlh',
    PROTOCOL_GAME_NLH_START = 'lobby_protocol_game_NLH_start',
    GAME_PLO = 'game_plo',
    GAME_OFC = 'game_ofc',
    GAME_TEEN_PATTI = 'game_teen_patti',
    // 連接遊戲server
    LOBBY_TO_GAME = 'lobby_to_game',
    PROTOCOL_SERVER_LEAVEDESK = 'lobby_protocol_server_leaveDesk'
}
